### ISSUE TITLE
odiaA/2

### ISSUE THREAD

**Issue by Maxi-F** [carorinaldi/ParadigmasDeProgramacion#10]
No hay mención la cual indique que la tía Agatha no se puede odiar a si misma.

https://github.com/carorinaldi/ParadigmasDeProgramacion/blob/9fe436a595f6714ca23e2be3b108214f04e18f81/Logico/muerteEnLaMansionDreadbury.pl#L14-L17

**Comment by carorinaldi** [comment]
Ahí lo corregí, di por hecho que no se odiaba a si misma es verdad. Me quedó que la tía se suicida jajaj esta bien?
