### ISSUE TITLE
juegoFinal

### ISSUE THREAD

**Issue by Maxi-F** [carorinaldi/ParadigmasDeProgramacion#7]
Ojo con los retornos de strings. Si bien está bueno para verlo en la consola, lo que era necesario es retornar al jugador.

Puede parecer rara esta corrección, pero está bueno dividir lo que es la parte lógica con la parte de presentación. Por ejemplo, si se pidiera modificar las acciones del jugador ganador de la ronda, ¿Lo podría hacer con esta función?

Lo que sí se podría realizar es una función que retorne un String mostrando quién es el jugador ganador, para mostrarlo en pantalla, y esta función es la que se utiliza de manera de "presentación" en consola (no es pedida en el TP pero a modo de ejemplo)

https://github.com/carorinaldi/ParadigmasDeProgramacion/blob/3fd5f322dc3e88268e818a223ce3a9b9fd0503b5/Haskell/monopoly.hs#L70-L73

**Comment by Maxi-F** [comment]
Algo que me olvidé de  notar de esta función es que la composición `dinero.realizarTodasLasAcciones` se podría abstraer para no repetir la lógica en ambos jugadores

**Comment by carorinaldi** [comment]
Agregue la funcion dineroUltimaRonda para no repetir lógica en ambos jugadores, cambie la función juegoFinal con la función anterior agregada y muestro el participante ganador (después de realizar todas las acciones en la ultima ronda) en vez del String como lo mostraba antes
