### ISSUE TITLE
subastar - Repeticiones de lógica

### ISSUE THREAD

**Issue by Maxi-F** [carorinaldi/ParadigmasDeProgramacion#8]
Un par de repeticiones de lógica de subastar y sus funciones auxiliares:

Acá se está pidiendo la táctica y se la compara con una tactica en particular. Capaz se podria abstraer! (Tal vez con pattern matching salga una buena solucion :eyes: )
https://github.com/carorinaldi/ParadigmasDeProgramacion/blob/b378bce6e1dcb42e58b2db9556a93fb84f41edc1/Haskell/monopoly.hs#L53-L57

Subastar tiene dos ramas por las cuales se retorna lo mismo, ¿No estaría mejor retornarlo en una sola rama de la guarda?
https://github.com/carorinaldi/ParadigmasDeProgramacion/blob/b378bce6e1dcb42e58b2db9556a93fb84f41edc1/Haskell/monopoly.hs#L63-L67

**Comment by carorinaldi** [comment]
Cambie las dos funciones que repetían lógica por una llamada tieneTactica que recibe un  String un Participante y retorna el Booleano. También, como me marcaste lo de subastar que tenia dos ramas que retornaban lo mismo, lo deje solo en una y separe las condiciones por un or (||)
