### ISSUE TITLE
Calculo de alquileres: Declaratividad

### ISSUE THREAD

**Issue by Maxi-F** [carorinaldi/ParadigmasDeProgramacion#9]
Mirando un poco la solución:

https://github.com/carorinaldi/ParadigmasDeProgramacion/blob/b378bce6e1dcb42e58b2db9556a93fb84f41edc1/Haskell/monopoly.hs#L70-L80

Y viendo lo que nos pide el ejercicio:

```
cobrarAlquileres: suma $10 por cada propiedad barata y $20 por cada propiedad cara obtenida. 
Las propiedades baratas son aquellas cuyo precio es menor a $150.
```

¿No hay algo raro en la solución, en parte por la declaratividad? Si bien se entiende que se están obteniendo las cantidades menores y mayores a $150, hay bastante lógica algorítmica (filtrar las propiedades baratas y caras de la lista de propiedades de la persona jugadora, obtener la cantidad de propiedades, y a eso multiplicarlo por su valor).

Para hacerlo más declarativo, se podría empezar dividiendo en partes mas pequeñas el problema:
`Las propiedades baratas son aquellas cuyo precio es menor a $150.`
`Las propiedades baratas valen $10, las propiedades caras valen $20.`
`cobrarAlquileres suma al participante los valores de los alquileres de sus propiedades.`

Al dividirlo así, ¡Se pueden hacer funciones que me ayuden a solucionar el problema de una manera más declarativa! Tomando estas premisas, podriamos hacer 3 funciones:

`esPropiedadBarata`
`valorAlquiler`
`cobrarAlquileres`

Te dejo que intentes resolverlo con estas 3 funciones!

**Comment by carorinaldi** [comment]
Agregue las funciones sugeridas para hacerlo mas declarativo y borre las funciones que quedaban de mas como esPropiedadCara y cantidadPropiedadSegun
